# Generated by Django 2.1 on 2021-12-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='content_profile',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
